import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { serverUser } from "@/lib/serveruser";
import { QueryProvider } from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { getAgent } from "@/lib/getAgent";
import { getUserRole } from "@/lib/getUserRole";
import { auth } from "@/auth";
import { Footer } from "@/components/footer";
import { getAgentId } from "@/lib/getAgentId";

export const metadata: Metadata = {
  title: "Apartamenti",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await serverUser();
  const userRole = await getUserRole()
  const agentId = await getAgentId()
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <QueryProvider>
          <Navbar user={user} userRole = {userRole} agent={agentId} />
          {children}
         <Footer />
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
